cortex_version: 1

system:
  name: "toy-run"
  description: "Example EEG benchmark with fake data"

dataset:
  path: "datasets/fake/test.raw"
  format: "raw"
  channels: 4
  sample_rate_hz: 160

realtime:
  scheduler: fifo          # fifo | rr | other
  priority: 85             # requires privileges to take effect
  cpu_affinity: [0]        # pick a core that surely exists
  deadline_ms: 500         # hop(80) / Fs(160) = 500 ms

power:
  governor: "performance"
  turbo: false

benchmark:
  metrics: [latency, jitter, throughput, memory_usage, energy_consumption]
  parameters:
    duration_seconds: 5
    repeats: 1
    warmup_seconds: 1
  load_profile: "idle"

output:
  directory: "results/example"
  format: "json"
  include_raw_data: false

plugins:
  - name: "car"
    status: ready
    spec_uri: "kernels/v1/car@f32"
    spec_version: "1.0.0"
  
  - name: "notch_iir"
    status: ready
    spec_uri: "kernels/v1/notch_iir@f32"
    spec_version: "1.0.0"
    params:  # Optional: kernel-specific parameters
      f0_hz: 60.0
      Q: 30.0
