cortex_version: 1

system:
  name: "toy-run"
  description: "Example EEG benchmark with fake data"

dataset:
  path: "datasets/fake/test.raw"
  format: "raw"
  channels: 4
  sample_rate_hz: 160

realtime:
  scheduler: fifo          # fifo | rr | other
  priority: 85             # requires privileges to take effect
  cpu_affinity: [0]        # pick a core that surely exists
  deadline_ms: 50          # hop(8) / Fs(160) = 50 ms

power:
  governor: "performance"
  turbo: false

benchmark:
  metrics: [latency, jitter, throughput, memory_usage, energy_consumption]
  parameters:
    duration_seconds: 5
    repeats: 1
    warmup_seconds: 1
  load_profile: "idle"

output:
  directory: "results/example"
  format: "json"
  include_raw_data: false

plugins:
  - name: "notch_iir"
    status: draft                 # draft | ready
    spec_uri: null                # fill when spec lands
    spec_version: null
    runtime:
      window_length_samples: 16
      hop_samples: 8
      channels: 4
      dtype: "float32"
      allow_in_place: false
    params: {}                    # TBD: f0_hz, Q
    tolerances: null              # abs/rel once defined
    oracle: null                  # path to gold bundle later

  - name: "car"
    status: draft
    spec_uri: null
    spec_version: null
    runtime:
      window_length_samples: 16
      hop_samples: 8
      channels: 4
      dtype: "float32"
      allow_in_place: true
    params: {}                    # TBD: exclude_channels
    tolerances: null
    oracle: null
